name: Swift

on:
  push:
    branches: [master, '[0-9]+.[0-9]+.[0-9]+']
    tags: ['[0-9]+.[0-9]+.[0-9]+*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Show versions
        run: |
          xcodebuild -version
          swift --version
      
      - name: Build and test
        run: |
          swift build -v
          swift test -v
