name: Swift

on:
  push:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.[0-9]+'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build with Xcode on macOS 26
    runs-on: macos-26
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Show Xcode and Swift version
        run: |
          xcodebuild -version
          swift --version
      
      - name: Build
        run: swift build -v
      
      - name: Run tests
        run: swift test -v
