name: iOS CI

on:
  push:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.[0-9]+'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-26
    defaults:
      run:
        working-directory: Examples/OrchardDemo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode and Swift version
        run: |
          xcodebuild -version
          swift --version

      - name: Detect Xcode project
        id: detect_project
        run: |
          PROJECT_FILE=$(find . -name "*.xcodeproj" -maxdepth 1 | head -n 1)
          echo "project=$PROJECT_FILE" >> $GITHUB_OUTPUT

      - name: Detect scheme
        id: detect_scheme
        run: |
          SCHEME=$(xcodebuild -list -json -project ${{ steps.detect_project.outputs.project }} | jq -r '.project.schemes[0]')
          echo "scheme=$SCHEME" >> $GITHUB_OUTPUT

      - name: Build iOS app
        run: |
          xcodebuild \
            -project ${{ steps.detect_project.outputs.project }} \
            -scheme ${{ steps.detect_scheme.outputs.scheme }} \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            clean build
